# PHP + Apache
#
# VERSION               0.0.1

FROM php:5.6-apache
MAINTAINER Eloy Lopez <elswork@gmail.com>

LABEL Description="Crea Servidor Apache con PHP y carga directorio src" Vendor="deft.work" Version="1.0"
RUN apt-get update && apt-get install -y \
    # git \
    # vim \
    # ... \   
    apt-get clean
# COPY config/php.ini /usr/local/etc/php/
COPY src/ /var/www/html/
# open port 80 
EXPOSE  80 